<?php

defined('BASE_PATH') || exit('Acesso direto nao permitido.');

return [
    ['GET', '/api/v1/health', [ApiController::class, 'health']],
    ['POST', '/api/v1/auth/token', [ApiController::class, 'token']],
    ['GET', '/api/v1/me', [ApiController::class, 'me'], ['api']],
    ['GET', '/api/v1/courses', [ApiController::class, 'courses']],
    ['GET', '/api/v1/courses/{id}', [ApiController::class, 'course']],
    ['GET', '/api/v1/plans', [ApiController::class, 'plans']],
    ['GET', '/api/v1/ranking', [ApiController::class, 'ranking']],
    ['GET', '/api/v1/certificates/{code}/validate', [ApiController::class, 'validateCertificate']],

    ['GET', '/', [PublicController::class, 'home']],
    ['GET', '/sobre', [PublicController::class, 'about']],
    ['GET', '/cursos', [PublicController::class, 'courses']],
    ['GET', '/eventos', [EventController::class, 'index']],
    ['GET', '/eventos/{id}', [EventController::class, 'show']],
    ['POST', '/eventos/{id}/inscrever', [EventController::class, 'register'], ['auth']],
    ['GET', '/comunidade', [CommunityController::class, 'index']],
    ['POST', '/comunidade', [CommunityController::class, 'store'], ['auth']],
    ['GET', '/comunidade/{id}', [CommunityController::class, 'show'], ['auth']],
    ['POST', '/comunidade/{id}/comentar', [CommunityController::class, 'comment'], ['auth']],
    ['POST', '/comunidade/{id}/curtir', [CommunityController::class, 'like'], ['auth']],
    ['POST', '/comunidade/{id}/salvar', [CommunityController::class, 'save'], ['auth']],

    ['GET', '/certificados/validar', [CertificateController::class, 'validateForm']],
    ['POST', '/certificados/validar', [CertificateController::class, 'validatePost']],
    ['GET', '/certificados/validar/{code}', [CertificateController::class, 'validateCode']],

    ['GET', '/biblioteca', [LibraryController::class, 'index']],
    ['GET', '/biblioteca/enviar', [LibraryController::class, 'contribute'], ['auth', 'role:aluno,professor']],
    ['POST', '/biblioteca/enviar', [LibraryController::class, 'storeContribution'], ['auth', 'role:aluno,professor']],
    ['GET', '/biblioteca/favoritos', [LibraryController::class, 'favorites'], ['auth']],
    ['GET', '/biblioteca/{id}', [LibraryController::class, 'show']],
    ['POST', '/biblioteca/{id}/favoritar', [LibraryController::class, 'toggleFavorite'], ['auth']],

    ['GET', '/planos', [PlanController::class, 'index']],
    ['POST', '/planos/{id}/assinar', [PlanController::class, 'subscribe'], ['auth']],

    ['GET', '/login', [AuthController::class, 'showLogin']],
    ['POST', '/login', [AuthController::class, 'login']],
    ['GET', '/cadastro', [AuthController::class, 'showRegister']],
    ['POST', '/cadastro', [AuthController::class, 'register']],
    ['POST', '/logout', [AuthController::class, 'logout'], ['auth']],

    ['GET', '/instituicoes/buscar', [InstitutionController::class, 'search']],

    ['GET', '/portal', [PortalController::class, 'index'], ['auth']],
    ['GET', '/inicio', [PortalController::class, 'index'], ['auth']],
    ['GET', '/perfil', [ProfileController::class, 'index'], ['auth']],
    ['GET', '/configuracoes', [ProfileController::class, 'index'], ['auth']],
    ['POST', '/perfil/dados', [ProfileController::class, 'updateProfile'], ['auth']],
    ['POST', '/perfil/aparencia', [ProfileController::class, 'updateAppearance'], ['auth']],
    ['POST', '/perfil/senha', [ProfileController::class, 'updatePassword'], ['auth']],
    ['GET', '/financeiro', [FinanceController::class, 'index'], ['auth']],
    ['GET', '/notificacoes', [NotificationController::class, 'index'], ['auth']],
    ['POST', '/notificacoes/ler-todas', [NotificationController::class, 'markAllRead'], ['auth']],
    ['POST', '/notificacoes/{id}/ler', [NotificationController::class, 'markRead'], ['auth']],
    ['POST', '/notificacoes/{id}/nao-lida', [NotificationController::class, 'markUnread'], ['auth']],
    ['GET', '/analytics', [AnalyticsController::class, 'index'], ['auth', 'role:administrador,supervisor']],
    ['GET', '/ranking', [RankingController::class, 'index'], ['auth']],
    ['GET', '/turmas', [ClassController::class, 'myClasses'], ['auth', 'role:aluno,professor']],
    ['GET', '/turmas/{id}', [ClassController::class, 'show'], ['auth', 'role:aluno,professor']],
    ['GET', '/frequencia', [AttendanceController::class, 'index'], ['auth', 'role:professor,administrador,supervisor']],
    ['POST', '/frequencia', [AttendanceController::class, 'store'], ['auth', 'role:professor,administrador,supervisor']],
    ['GET', '/frequencia/relatorio', [AttendanceController::class, 'report'], ['auth', 'role:professor,administrador,supervisor']],
    ['GET', '/minha-frequencia', [AttendanceController::class, 'myAttendance'], ['auth', 'role:aluno,professor']],
    ['GET', '/chat', [ChatController::class, 'index'], ['auth']],
    ['POST', '/chat/privado', [ChatController::class, 'startPrivate'], ['auth']],
    ['POST', '/chat/{channelId}/enviar', [ChatController::class, 'send'], ['auth']],

    ['GET', '/dashboard', [DashboardController::class, 'index'], ['auth']],
    ['POST', '/settings', [DashboardController::class, 'updateSettings'], ['auth']],

    ['GET', '/certificados', [CertificateController::class, 'index'], ['auth', 'role:aluno,professor']],
    ['GET', '/certificados/ver/{code}', [CertificateController::class, 'show'], ['auth']],

    ['GET', '/atividades', [ActivityController::class, 'myActivities'], ['auth', 'role:aluno,professor']],
    ['GET', '/atividades/{id}', [ActivityController::class, 'showForStudent'], ['auth', 'role:aluno,professor']],
    ['POST', '/atividades/{id}/entregar', [ActivityController::class, 'submit'], ['auth', 'role:aluno,professor']],
    ['GET', '/boletim', [ActivityController::class, 'gradebook'], ['auth', 'role:aluno,professor']],
    ['GET', '/provas', [ExamController::class, 'index'], ['auth', 'role:aluno,professor']],
    ['GET', '/provas/tentativas/{attemptId}', [ExamController::class, 'attempt'], ['auth', 'role:aluno,professor']],
    ['POST', '/provas/tentativas/{attemptId}/enviar', [ExamController::class, 'submit'], ['auth', 'role:aluno,professor']],
    ['GET', '/provas/tentativas/{attemptId}/resultado', [ExamController::class, 'result'], ['auth', 'role:aluno,professor']],
    ['GET', '/provas/{id}', [ExamController::class, 'show'], ['auth', 'role:aluno,professor']],
    ['POST', '/provas/{id}/iniciar', [ExamController::class, 'start'], ['auth', 'role:aluno,professor']],

    ['GET', '/aluno/cursos', [CourseCatalogController::class, 'index'], ['auth', 'role:aluno,professor']],
    ['GET', '/aluno/cursos/{id}', [CourseCatalogController::class, 'show'], ['auth', 'role:aluno,professor']],
    ['POST', '/aluno/cursos/{id}/matricular', [CourseCatalogController::class, 'enroll'], ['auth', 'role:aluno,professor']],
    ['GET', '/meus-cursos', [CourseCatalogController::class, 'myCourses'], ['auth', 'role:aluno,professor']],
    ['GET', '/meus-cursos/{id}', [CourseCatalogController::class, 'enrollment'], ['auth', 'role:aluno,professor']],
    ['POST', '/meus-cursos/{enrollmentId}/aulas/{lessonId}/concluir', [CourseCatalogController::class, 'completeLesson'], ['auth', 'role:aluno,professor']],
    ['GET', '/aluno/meus-cursos', [CourseCatalogController::class, 'myCourses'], ['auth', 'role:aluno,professor']],
    ['GET', '/aluno/meus-cursos/{id}', [CourseCatalogController::class, 'enrollment'], ['auth', 'role:aluno,professor']],
    ['POST', '/aluno/meus-cursos/{enrollmentId}/aulas/{lessonId}/concluir', [CourseCatalogController::class, 'completeLesson'], ['auth', 'role:aluno,professor']],

    ['GET', '/admin/contas-pendentes', [AdminController::class, 'pendingAccounts'], ['auth', 'role:administrador,supervisor']],
    ['GET', '/admin/busca', [AdminController::class, 'search'], ['auth', 'role:administrador,supervisor']],
    ['GET', '/admin/usuarios', [AdminController::class, 'users'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/usuarios/{id}/atualizar', [AdminController::class, 'updateUser'], ['auth', 'role:administrador,supervisor']],
    ['GET', '/admin/permissoes', [AdminController::class, 'permissions'], ['auth', 'role:administrador,supervisor']],
    ['GET', '/admin/categorias', [AdminController::class, 'categories'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/categorias/renomear', [AdminController::class, 'renameCategory'], ['auth', 'role:administrador,supervisor']],
    ['GET', '/admin/logs', [AdminController::class, 'logs'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/contas/{id}/aprovar', [AdminController::class, 'approve'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/contas/{id}/recusar', [AdminController::class, 'reject'], ['auth', 'role:administrador,supervisor']],
    ['GET', '/admin/planos', [PlanController::class, 'adminIndex'], ['auth', 'role:administrador,supervisor']],
    ['GET', '/admin/planos/novo', [PlanController::class, 'create'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/planos', [PlanController::class, 'store'], ['auth', 'role:administrador,supervisor']],
    ['GET', '/admin/planos/{id}/editar', [PlanController::class, 'edit'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/planos/{id}/atualizar', [PlanController::class, 'update'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/planos/{id}/desativar', [PlanController::class, 'archive'], ['auth', 'role:administrador,supervisor']],
    ['GET', '/admin/matriculas', [AdminEnrollmentController::class, 'index'], ['auth', 'role:administrador,supervisor']],
    ['GET', '/admin/certificados', [CertificateController::class, 'adminIndex'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/certificados/{id}/revogar', [CertificateController::class, 'revoke'], ['auth', 'role:administrador,supervisor']],
    ['GET', '/admin/comunidade', [CommunityController::class, 'adminIndex'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/comunidade/{id}/aprovar', [CommunityController::class, 'approve'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/comunidade/{id}/recusar', [CommunityController::class, 'reject'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/comunidade/{id}/arquivar', [CommunityController::class, 'archive'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/comunidade/{id}/destacar', [CommunityController::class, 'feature'], ['auth', 'role:administrador,supervisor']],
    ['GET', '/admin/eventos', [EventController::class, 'adminIndex'], ['auth', 'role:administrador,supervisor']],
    ['GET', '/admin/eventos/novo', [EventController::class, 'create'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/eventos', [EventController::class, 'store'], ['auth', 'role:administrador,supervisor']],
    ['GET', '/admin/eventos/{id}', [EventController::class, 'adminShow'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/eventos/{id}/status', [EventController::class, 'updateStatus'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/eventos/inscricoes/{registrationId}/presenca', [EventController::class, 'confirmPresence'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/eventos/inscricoes/{registrationId}/certificado', [EventController::class, 'issueCertificate'], ['auth', 'role:administrador,supervisor']],
    ['GET', '/admin/turmas', [AdminClassController::class, 'index'], ['auth', 'role:administrador,supervisor']],
    ['GET', '/admin/turmas/nova', [AdminClassController::class, 'createClass'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/turmas', [AdminClassController::class, 'storeClass'], ['auth', 'role:administrador,supervisor']],
    ['GET', '/admin/turmas/{id}/editar', [AdminClassController::class, 'editClass'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/turmas/{id}/atualizar', [AdminClassController::class, 'updateClass'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/turmas/{id}/arquivar', [AdminClassController::class, 'archiveClass'], ['auth', 'role:administrador,supervisor']],
    ['GET', '/admin/turmas/{id}', [AdminClassController::class, 'showClass'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/turmas/{id}/alunos', [AdminClassController::class, 'linkStudent'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/turmas/{id}/professores', [AdminClassController::class, 'linkTeacher'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/turmas/{id}/disciplinas', [AdminClassController::class, 'linkSubject'], ['auth', 'role:administrador,supervisor']],
    ['GET', '/admin/disciplinas/nova', [AdminClassController::class, 'createSubject'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/disciplinas', [AdminClassController::class, 'storeSubject'], ['auth', 'role:administrador,supervisor']],
    ['GET', '/admin/disciplinas/{id}/editar', [AdminClassController::class, 'editSubject'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/disciplinas/{id}/atualizar', [AdminClassController::class, 'updateSubject'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/disciplinas/{id}/arquivar', [AdminClassController::class, 'archiveSubject'], ['auth', 'role:administrador,supervisor']],
    ['GET', '/admin/chat', [ChatController::class, 'audit'], ['auth', 'role:administrador,supervisor']],
    ['GET', '/admin/provas', [ExamController::class, 'adminIndex'], ['auth', 'role:professor,administrador,supervisor']],
    ['GET', '/admin/provas/nova', [ExamController::class, 'create'], ['auth', 'role:professor,administrador,supervisor']],
    ['POST', '/admin/provas', [ExamController::class, 'store'], ['auth', 'role:professor,administrador,supervisor']],
    ['GET', '/admin/provas/tentativas/{attemptId}', [ExamController::class, 'adminAttempt'], ['auth', 'role:professor,administrador,supervisor']],
    ['POST', '/admin/provas/tentativas/{attemptId}/corrigir', [ExamController::class, 'gradeAttempt'], ['auth', 'role:professor,administrador,supervisor']],
    ['GET', '/admin/provas/{id}', [ExamController::class, 'adminShow'], ['auth', 'role:professor,administrador,supervisor']],
    ['POST', '/admin/provas/{id}/questoes', [ExamController::class, 'storeQuestion'], ['auth', 'role:professor,administrador,supervisor']],

    ['GET', '/admin/atividades', [ActivityController::class, 'adminIndex'], ['auth', 'role:professor,administrador,supervisor']],
    ['GET', '/admin/atividades/nova', [ActivityController::class, 'create'], ['auth', 'role:professor,administrador,supervisor']],
    ['POST', '/admin/atividades', [ActivityController::class, 'store'], ['auth', 'role:professor,administrador,supervisor']],
    ['GET', '/admin/atividades/{id}', [ActivityController::class, 'adminShow'], ['auth', 'role:professor,administrador,supervisor']],
    ['GET', '/admin/atividades/{id}/editar', [ActivityController::class, 'edit'], ['auth', 'role:professor,administrador,supervisor']],
    ['POST', '/admin/atividades/{id}/atualizar', [ActivityController::class, 'update'], ['auth', 'role:professor,administrador,supervisor']],
    ['POST', '/admin/atividades/{id}/encerrar', [ActivityController::class, 'archive'], ['auth', 'role:professor,administrador,supervisor']],
    ['POST', '/admin/atividades/entregas/{submissionId}/corrigir', [ActivityController::class, 'gradeSubmission'], ['auth', 'role:professor,administrador,supervisor']],

    ['GET', '/admin/biblioteca', [LibraryController::class, 'adminIndex'], ['auth', 'role:professor,administrador,supervisor']],
    ['GET', '/admin/biblioteca/novo', [LibraryController::class, 'create'], ['auth', 'role:professor,administrador,supervisor']],
    ['POST', '/admin/biblioteca', [LibraryController::class, 'store'], ['auth', 'role:professor,administrador,supervisor']],
    ['GET', '/admin/biblioteca/{id}/editar', [LibraryController::class, 'edit'], ['auth', 'role:professor,administrador,supervisor']],
    ['POST', '/admin/biblioteca/{id}/atualizar', [LibraryController::class, 'update'], ['auth', 'role:professor,administrador,supervisor']],
    ['POST', '/admin/biblioteca/{id}/aprovar', [LibraryController::class, 'approve'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/biblioteca/{id}/recusar', [LibraryController::class, 'reject'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/biblioteca/{id}/arquivar', [LibraryController::class, 'archive'], ['auth', 'role:professor,administrador,supervisor']],

    ['GET', '/admin/cursos', [AdminCourseController::class, 'index'], ['auth', 'role:administrador,supervisor']],
    ['GET', '/admin/cursos/novo', [AdminCourseController::class, 'create'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/cursos', [AdminCourseController::class, 'store'], ['auth', 'role:administrador,supervisor']],
    ['GET', '/admin/cursos/{id}', [AdminCourseController::class, 'show'], ['auth', 'role:administrador,supervisor']],
    ['GET', '/admin/cursos/{id}/editar', [AdminCourseController::class, 'edit'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/cursos/{id}/atualizar', [AdminCourseController::class, 'update'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/cursos/{id}/desativar', [AdminCourseController::class, 'deactivate'], ['auth', 'role:administrador,supervisor']],

    ['GET', '/admin/cursos/{courseId}/modulos/novo', [AdminCourseController::class, 'createModule'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/cursos/{courseId}/modulos', [AdminCourseController::class, 'storeModule'], ['auth', 'role:administrador,supervisor']],
    ['GET', '/admin/cursos/{courseId}/modulos/{moduleId}/editar', [AdminCourseController::class, 'editModule'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/cursos/{courseId}/modulos/{moduleId}/atualizar', [AdminCourseController::class, 'updateModule'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/cursos/{courseId}/modulos/{moduleId}/excluir', [AdminCourseController::class, 'deleteModule'], ['auth', 'role:administrador,supervisor']],

    ['GET', '/admin/cursos/{courseId}/aulas/novo', [AdminCourseController::class, 'createLesson'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/cursos/{courseId}/aulas', [AdminCourseController::class, 'storeLesson'], ['auth', 'role:administrador,supervisor']],
    ['GET', '/admin/cursos/{courseId}/aulas/{lessonId}/editar', [AdminCourseController::class, 'editLesson'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/cursos/{courseId}/aulas/{lessonId}/atualizar', [AdminCourseController::class, 'updateLesson'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/cursos/{courseId}/aulas/{lessonId}/excluir', [AdminCourseController::class, 'deleteLesson'], ['auth', 'role:administrador,supervisor']],

    ['GET', '/admin/cursos/{courseId}/aulas/{lessonId}/materiais/novo', [AdminCourseController::class, 'createMaterial'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/cursos/{courseId}/aulas/{lessonId}/materiais', [AdminCourseController::class, 'storeMaterial'], ['auth', 'role:administrador,supervisor']],
    ['GET', '/admin/cursos/{courseId}/aulas/{lessonId}/materiais/{materialId}/editar', [AdminCourseController::class, 'editMaterial'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/cursos/{courseId}/aulas/{lessonId}/materiais/{materialId}/atualizar', [AdminCourseController::class, 'updateMaterial'], ['auth', 'role:administrador,supervisor']],
    ['POST', '/admin/cursos/{courseId}/aulas/{lessonId}/materiais/{materialId}/excluir', [AdminCourseController::class, 'deleteMaterial'], ['auth', 'role:administrador,supervisor']],
];
